### ISSUE TITLE
BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序

### ISSUE THREAD

**Issue by JIKEXIU** [1299172402/BBDown_GUI#4]
新版的BBDown_GUI_v1.0.3解析出来的链接默认排序是 HEVC，下载视频编码格式选择了 AVC 也不行。我想下载高码率的AVC，只能交互式选择清晰度。
![QQ截图20220517235719](https://user-images.githubusercontent.com/53504145/168943756-bb4002ec-a1eb-4c2b-9319-f4cd274528b5.png)
![QQ截图20220517235812](https://user-images.githubusercontent.com/53504145/168944231-3b02f12b-f553-4d75-a815-2c28c575908d.png)
下面这个图是用BBDown命令解析的链接，它是按照文件码率大小排序的。我问了BBDown作者，他的回复是按照文件码率大小排序的，不是默认HEVC。
![QQ截图20220517235848](https://user-images.githubusercontent.com/53504145/168944458-27c2ca55-4b36-4e69-bc23-8a2868242624.png)
你看下是哪里问题，习惯了之前版本自动下载，默认选择文件高码率AVC。

**Comment by 1299172402** [comment]
有大陆的地址吗，要不然我没办法测试

或者正确的BBDown的命令也麻烦给一下

**Comment by 1299172402** [comment]
已查明，下一版修复

**Comment by JIKEXIU** [comment]
> 有大陆的地址吗，要不然我没办法测试
> 
> 或者正确的BBDown的命令也麻烦给一下

用这个命令解析 bbdown -intl -info -c "cookie"  epxxx

**Comment by 1299172402** [comment]
你能测试一下吗，如果没问题我再发布

https://zhiyuyu.lanzout.com/ikx3F057fbsh

**Comment by JIKEXIU** [comment]
> 你能测试一下吗，如果没问题我再发布
> 
> https://zhiyuyu.lanzout.com/iB7BI057h7wj

感谢大佬，我今天没时间，明天测试后给你答复。

**Comment by JIKEXIU** [comment]
> 你能测试一下吗，如果没问题我再发布
> 
> https://pan.lanzoui.com/iB7BI057h7wj

**Comment by JIKEXIU** [comment]
大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。
发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。
![QQ截图20220522213833](https://user-images.githubusercontent.com/53504145/169698906-bbed6420-be27-4c5e-ab95-78d8a6094f57.png)
![QQ截图20220522210231](https://user-images.githubusercontent.com/53504145/169698912-9076a439-68f8-42e2-8f27-ff7394e168ea.png)

**Comment by 1299172402** [comment]
你开一下BBdown的调试模式，看一下他里面有没有字幕流混进去，如果有的话，那可能是播放器的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月22日(周日) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)




 
大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。
 发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。

**Comment by JIKEXIU** [comment]
> 你开一下BBdown的调试模式，看一下他里面有没有字幕流混进去，如果有的话，那可能是播放器的问题
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2022年5月22日(周日) 晚上10:01
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)
> 
> 
> 
> 
>  
> 大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。
>  发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。
>  
>  
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

不是混流播放的问题，字幕混流播放是能呈现多个字幕。我指的是国际端勾选仅下载字幕，无论单P还是多P完成后，文件夹就只保留一个字幕了，我想把字幕单独下载下来，不混流。

**Comment by 1299172402** [comment]
这我就不知道是什么原因了，你可以尝试开一下跳过混流，这样子应该是bbdown应该会把字幕都会下载到文件夹里。或者去问bbdown原作者一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月22日(周日) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)




  
你开一下BBdown的调试模式，看一下他里面有没有字幕流混进去，如果有的话，那可能是播放器的问题
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2022年5月22日(周日) 晚上10:01
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)
 
大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。
 发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
不是混流播放的问题，字幕混流播放是能呈现多个字幕。我指的是国际端勾选仅下载字幕，无论单P还是多P完成后，文件夹就只保留一个字幕了，我想把字幕单独下载下来，不混流。

**Comment by 1299172402** [comment]
我也测试了下其他多语言字幕的下载，应该是bbdown自身的原因，应该可以向他反馈一下


详情如下：
当bbdown启用了仅下载字幕的时候，由于字幕的输出文件名是一样的（分P号加上视频标题），而不会像常规下载的临时文件那样在末尾加上zh_CN或者jp，所以导致后面下载的字幕会覆盖掉之前下载的字幕



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月22日(周日) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)




  
你开一下BBdown的调试模式，看一下他里面有没有字幕流混进去，如果有的话，那可能是播放器的问题
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2022年5月22日(周日) 晚上10:01
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4)
 
大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。
 发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
不是混流播放的问题，字幕混流播放是能呈现多个字幕。我指的是国际端勾选仅下载字幕，无论单P还是多P完成后，文件夹就只保留一个字幕了，我想把字幕单独下载下来，不混流。

**Comment by JIKEXIU** [comment]
> 我也测试了下其他多语言字幕的下载，应该是bbdown自身的原因，应该可以向他反馈一下 详情如下： 当bbdown启用了仅下载字幕的时候，由于字幕的输出文件名是一样的（分P号加上视频标题），而不会像常规下载的临时文件那样在末尾加上zh_CN或者jp，所以导致后面下载的字幕会覆盖掉之前下载的字幕
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月22日(周日) 晚上10:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4) 你开一下BBdown的调试模式，看一下他里面有没有字幕流混进去，如果有的话，那可能是播放器的问题
> ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年5月22日(周日) 晚上10:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [1299172402/BBDown_GUI] BBDown_GUI_v1.0.3解析的链接自动下载默认排序是HEVC，BBDown 命令解析的是按照文件码率大小来排序 (Issue #4) 大佬，我对逐个功能（大陆/国际）进行了测试，之前的问题已经解决。 发现一个新问题：国际端勾选仅下载字幕，单P或多P完成后只剩下一个字幕了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 不是混流播放的问题，字幕混流播放是能呈现多个字幕。我指的是国际端勾选仅下载字幕，无论单P还是多P完成后，文件夹就只保留一个字幕了，我想把字幕单独下载下来，不混流。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个我也注意到了，所以不确定是gui的问题还是BBDown的问题。

**Comment by 1299172402** [comment]
应该是 BBDown 原因，麻烦你跟他说一下了
